title: Mike Anderson
description: Software Developer / Mathematician
show_downloads: false
permalink: /:title
auto: true
highlighter: pygments
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
collections:
- sections
- projects
- work